export interface Voice {
  value: string;
  label: string;
  gender: string;
  lang: string;
}

export type TtsServer = "no-voice" | "azure-tts-v1" | "azure-tts-v2" | "siliconflow" | "gemini" | "mimo";

// 331 voces reales de Azure TTS (cargadas desde azure_voices.json del backend)
export const AZURE_VOICES: Voice[] = [
  { value: "af-ZA-AdriNeural-Female", label: "af-ZA-AdriNeural (Female)", gender: "Female", lang: "af-ZA" },
  { value: "af-ZA-WillemNeural-Male", label: "af-ZA-WillemNeural (Male)", gender: "Male", lang: "af-ZA" },
  { value: "am-ET-AmehaNeural-Male", label: "am-ET-AmehaNeural (Male)", gender: "Male", lang: "am-ET" },
  { value: "am-ET-MekdesNeural-Female", label: "am-ET-MekdesNeural (Female)", gender: "Female", lang: "am-ET" },
  { value: "ar-AE-FatimaNeural-Female", label: "ar-AE-FatimaNeural (Female)", gender: "Female", lang: "ar-AE" },
  { value: "ar-AE-HamdanNeural-Male", label: "ar-AE-HamdanNeural (Male)", gender: "Male", lang: "ar-AE" },
  { value: "ar-BH-AliNeural-Male", label: "ar-BH-AliNeural (Male)", gender: "Male", lang: "ar-BH" },
  { value: "ar-BH-LailaNeural-Female", label: "ar-BH-LailaNeural (Female)", gender: "Female", lang: "ar-BH" },
  { value: "ar-DZ-AminaNeural-Female", label: "ar-DZ-AminaNeural (Female)", gender: "Female", lang: "ar-DZ" },
  { value: "ar-DZ-IsmaelNeural-Male", label: "ar-DZ-IsmaelNeural (Male)", gender: "Male", lang: "ar-DZ" },
  { value: "ar-EG-SalmaNeural-Female", label: "ar-EG-SalmaNeural (Female)", gender: "Female", lang: "ar-EG" },
  { value: "ar-EG-ShakirNeural-Male", label: "ar-EG-ShakirNeural (Male)", gender: "Male", lang: "ar-EG" },
  { value: "ar-IQ-BasselNeural-Male", label: "ar-IQ-BasselNeural (Male)", gender: "Male", lang: "ar-IQ" },
  { value: "ar-IQ-RanaNeural-Female", label: "ar-IQ-RanaNeural (Female)", gender: "Female", lang: "ar-IQ" },
  { value: "ar-JO-SanaNeural-Female", label: "ar-JO-SanaNeural (Female)", gender: "Female", lang: "ar-JO" },
  { value: "ar-JO-TaimNeural-Male", label: "ar-JO-TaimNeural (Male)", gender: "Male", lang: "ar-JO" },
  { value: "ar-KW-FahedNeural-Male", label: "ar-KW-FahedNeural (Male)", gender: "Male", lang: "ar-KW" },
  { value: "ar-KW-NouraNeural-Female", label: "ar-KW-NouraNeural (Female)", gender: "Female", lang: "ar-KW" },
  { value: "ar-LB-LaylaNeural-Female", label: "ar-LB-LaylaNeural (Female)", gender: "Female", lang: "ar-LB" },
  { value: "ar-LB-RamiNeural-Male", label: "ar-LB-RamiNeural (Male)", gender: "Male", lang: "ar-LB" },
  { value: "ar-LY-ImanNeural-Female", label: "ar-LY-ImanNeural (Female)", gender: "Female", lang: "ar-LY" },
  { value: "ar-LY-OmarNeural-Male", label: "ar-LY-OmarNeural (Male)", gender: "Male", lang: "ar-LY" },
  { value: "ar-MA-JamalNeural-Male", label: "ar-MA-JamalNeural (Male)", gender: "Male", lang: "ar-MA" },
  { value: "ar-MA-MounaNeural-Female", label: "ar-MA-MounaNeural (Female)", gender: "Female", lang: "ar-MA" },
  { value: "ar-OM-AbdullahNeural-Male", label: "ar-OM-AbdullahNeural (Male)", gender: "Male", lang: "ar-OM" },
  { value: "ar-OM-AyshaNeural-Female", label: "ar-OM-AyshaNeural (Female)", gender: "Female", lang: "ar-OM" },
  { value: "ar-QA-AmalNeural-Female", label: "ar-QA-AmalNeural (Female)", gender: "Female", lang: "ar-QA" },
  { value: "ar-QA-MoazNeural-Male", label: "ar-QA-MoazNeural (Male)", gender: "Male", lang: "ar-QA" },
  { value: "ar-SA-HamedNeural-Male", label: "ar-SA-HamedNeural (Male)", gender: "Male", lang: "ar-SA" },
  { value: "ar-SA-ZariyahNeural-Female", label: "ar-SA-ZariyahNeural (Female)", gender: "Female", lang: "ar-SA" },
  { value: "ar-SY-AmanyNeural-Female", label: "ar-SY-AmanyNeural (Female)", gender: "Female", lang: "ar-SY" },
  { value: "ar-SY-LaithNeural-Male", label: "ar-SY-LaithNeural (Male)", gender: "Male", lang: "ar-SY" },
  { value: "ar-TN-HediNeural-Male", label: "ar-TN-HediNeural (Male)", gender: "Male", lang: "ar-TN" },
  { value: "ar-TN-ReemNeural-Female", label: "ar-TN-ReemNeural (Female)", gender: "Female", lang: "ar-TN" },
  { value: "ar-YE-MaryamNeural-Female", label: "ar-YE-MaryamNeural (Female)", gender: "Female", lang: "ar-YE" },
  { value: "ar-YE-SalehNeural-Male", label: "ar-YE-SalehNeural (Male)", gender: "Male", lang: "ar-YE" },
  { value: "az-AZ-BabekNeural-Male", label: "az-AZ-BabekNeural (Male)", gender: "Male", lang: "az-AZ" },
  { value: "az-AZ-BanuNeural-Female", label: "az-AZ-BanuNeural (Female)", gender: "Female", lang: "az-AZ" },
  { value: "bg-BG-BorislavNeural-Male", label: "bg-BG-BorislavNeural (Male)", gender: "Male", lang: "bg-BG" },
  { value: "bg-BG-KalinaNeural-Female", label: "bg-BG-KalinaNeural (Female)", gender: "Female", lang: "bg-BG" },
  { value: "bn-BD-NabanitaNeural-Female", label: "bn-BD-NabanitaNeural (Female)", gender: "Female", lang: "bn-BD" },
  { value: "bn-BD-PradeepNeural-Male", label: "bn-BD-PradeepNeural (Male)", gender: "Male", lang: "bn-BD" },
  { value: "bn-IN-BashkarNeural-Male", label: "bn-IN-BashkarNeural (Male)", gender: "Male", lang: "bn-IN" },
  { value: "bn-IN-TanishaaNeural-Female", label: "bn-IN-TanishaaNeural (Female)", gender: "Female", lang: "bn-IN" },
  { value: "bs-BA-GoranNeural-Male", label: "bs-BA-GoranNeural (Male)", gender: "Male", lang: "bs-BA" },
  { value: "bs-BA-VesnaNeural-Female", label: "bs-BA-VesnaNeural (Female)", gender: "Female", lang: "bs-BA" },
  { value: "ca-ES-EnricNeural-Male", label: "ca-ES-EnricNeural (Male)", gender: "Male", lang: "ca-ES" },
  { value: "ca-ES-JoanaNeural-Female", label: "ca-ES-JoanaNeural (Female)", gender: "Female", lang: "ca-ES" },
  { value: "cs-CZ-AntoninNeural-Male", label: "cs-CZ-AntoninNeural (Male)", gender: "Male", lang: "cs-CZ" },
  { value: "cs-CZ-VlastaNeural-Female", label: "cs-CZ-VlastaNeural (Female)", gender: "Female", lang: "cs-CZ" },
  { value: "cy-GB-AledNeural-Male", label: "cy-GB-AledNeural (Male)", gender: "Male", lang: "cy-GB" },
  { value: "cy-GB-NiaNeural-Female", label: "cy-GB-NiaNeural (Female)", gender: "Female", lang: "cy-GB" },
  { value: "da-DK-ChristelNeural-Female", label: "da-DK-ChristelNeural (Female)", gender: "Female", lang: "da-DK" },
  { value: "da-DK-JeppeNeural-Male", label: "da-DK-JeppeNeural (Male)", gender: "Male", lang: "da-DK" },
  { value: "de-AT-IngridNeural-Female", label: "de-AT-IngridNeural (Female)", gender: "Female", lang: "de-AT" },
  { value: "de-AT-JonasNeural-Male", label: "de-AT-JonasNeural (Male)", gender: "Male", lang: "de-AT" },
  { value: "de-CH-JanNeural-Male", label: "de-CH-JanNeural (Male)", gender: "Male", lang: "de-CH" },
  { value: "de-CH-LeniNeural-Female", label: "de-CH-LeniNeural (Female)", gender: "Female", lang: "de-CH" },
  { value: "de-DE-AmalaNeural-Female", label: "de-DE-AmalaNeural (Female)", gender: "Female", lang: "de-DE" },
  { value: "de-DE-ConradNeural-Male", label: "de-DE-ConradNeural (Male)", gender: "Male", lang: "de-DE" },
  { value: "de-DE-FlorianMultilingualNeural-Male", label: "de-DE-FlorianMultilingualNeural (Male)", gender: "Male", lang: "de-DE" },
  { value: "de-DE-KatjaNeural-Female", label: "de-DE-KatjaNeural (Female)", gender: "Female", lang: "de-DE" },
  { value: "de-DE-KillianNeural-Male", label: "de-DE-KillianNeural (Male)", gender: "Male", lang: "de-DE" },
  { value: "de-DE-SeraphinaMultilingualNeural-Female", label: "de-DE-SeraphinaMultilingualNeural (Female)", gender: "Female", lang: "de-DE" },
  { value: "el-GR-AthinaNeural-Female", label: "el-GR-AthinaNeural (Female)", gender: "Female", lang: "el-GR" },
  { value: "el-GR-NestorasNeural-Male", label: "el-GR-NestorasNeural (Male)", gender: "Male", lang: "el-GR" },
  { value: "en-AU-NatashaNeural-Female", label: "en-AU-NatashaNeural (Female)", gender: "Female", lang: "en-AU" },
  { value: "en-AU-WilliamNeural-Male", label: "en-AU-WilliamNeural (Male)", gender: "Male", lang: "en-AU" },
  { value: "en-CA-ClaraNeural-Female", label: "en-CA-ClaraNeural (Female)", gender: "Female", lang: "en-CA" },
  { value: "en-CA-LiamNeural-Male", label: "en-CA-LiamNeural (Male)", gender: "Male", lang: "en-CA" },
  { value: "en-GB-LibbyNeural-Female", label: "en-GB-LibbyNeural (Female)", gender: "Female", lang: "en-GB" },
  { value: "en-GB-MaisieNeural-Female", label: "en-GB-MaisieNeural (Female)", gender: "Female", lang: "en-GB" },
  { value: "en-GB-RyanNeural-Male", label: "en-GB-RyanNeural (Male)", gender: "Male", lang: "en-GB" },
  { value: "en-GB-SoniaNeural-Female", label: "en-GB-SoniaNeural (Female)", gender: "Female", lang: "en-GB" },
  { value: "en-GB-ThomasNeural-Male", label: "en-GB-ThomasNeural (Male)", gender: "Male", lang: "en-GB" },
  { value: "en-HK-SamNeural-Male", label: "en-HK-SamNeural (Male)", gender: "Male", lang: "en-HK" },
  { value: "en-HK-YanNeural-Female", label: "en-HK-YanNeural (Female)", gender: "Female", lang: "en-HK" },
  { value: "en-IE-ConnorNeural-Male", label: "en-IE-ConnorNeural (Male)", gender: "Male", lang: "en-IE" },
  { value: "en-IE-EmilyNeural-Female", label: "en-IE-EmilyNeural (Female)", gender: "Female", lang: "en-IE" },
  { value: "en-IN-NeerjaExpressiveNeural-Female", label: "en-IN-NeerjaExpressiveNeural (Female)", gender: "Female", lang: "en-IN" },
  { value: "en-IN-NeerjaNeural-Female", label: "en-IN-NeerjaNeural (Female)", gender: "Female", lang: "en-IN" },
  { value: "en-IN-PrabhatNeural-Male", label: "en-IN-PrabhatNeural (Male)", gender: "Male", lang: "en-IN" },
  { value: "en-KE-AsiliaNeural-Female", label: "en-KE-AsiliaNeural (Female)", gender: "Female", lang: "en-KE" },
  { value: "en-KE-ChilembaNeural-Male", label: "en-KE-ChilembaNeural (Male)", gender: "Male", lang: "en-KE" },
  { value: "en-NG-AbeoNeural-Male", label: "en-NG-AbeoNeural (Male)", gender: "Male", lang: "en-NG" },
  { value: "en-NG-EzinneNeural-Female", label: "en-NG-EzinneNeural (Female)", gender: "Female", lang: "en-NG" },
  { value: "en-NZ-MitchellNeural-Male", label: "en-NZ-MitchellNeural (Male)", gender: "Male", lang: "en-NZ" },
  { value: "en-NZ-MollyNeural-Female", label: "en-NZ-MollyNeural (Female)", gender: "Female", lang: "en-NZ" },
  { value: "en-PH-JamesNeural-Male", label: "en-PH-JamesNeural (Male)", gender: "Male", lang: "en-PH" },
  { value: "en-PH-RosaNeural-Female", label: "en-PH-RosaNeural (Female)", gender: "Female", lang: "en-PH" },
  { value: "en-SG-LunaNeural-Female", label: "en-SG-LunaNeural (Female)", gender: "Female", lang: "en-SG" },
  { value: "en-SG-WayneNeural-Male", label: "en-SG-WayneNeural (Male)", gender: "Male", lang: "en-SG" },
  { value: "en-TZ-ElimuNeural-Male", label: "en-TZ-ElimuNeural (Male)", gender: "Male", lang: "en-TZ" },
  { value: "en-TZ-ImaniNeural-Female", label: "en-TZ-ImaniNeural (Female)", gender: "Female", lang: "en-TZ" },
  { value: "en-US-AnaNeural-Female", label: "en-US-AnaNeural (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-AndrewMultilingualNeural-Male", label: "en-US-AndrewMultilingualNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-AndrewNeural-Male", label: "en-US-AndrewNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-AriaNeural-Female", label: "en-US-AriaNeural (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-AvaMultilingualNeural-Female", label: "en-US-AvaMultilingualNeural (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-AvaNeural-Female", label: "en-US-AvaNeural (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-BrianMultilingualNeural-Male", label: "en-US-BrianMultilingualNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-BrianNeural-Male", label: "en-US-BrianNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-ChristopherNeural-Male", label: "en-US-ChristopherNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-EmmaMultilingualNeural-Female", label: "en-US-EmmaMultilingualNeural (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-EmmaNeural-Female", label: "en-US-EmmaNeural (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-EricNeural-Male", label: "en-US-EricNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-GuyNeural-Male", label: "en-US-GuyNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-JennyNeural-Female", label: "en-US-JennyNeural (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-MichelleNeural-Female", label: "en-US-MichelleNeural (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-RogerNeural-Male", label: "en-US-RogerNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-SteffanNeural-Male", label: "en-US-SteffanNeural (Male)", gender: "Male", lang: "en-US" },
  { value: "en-ZA-LeahNeural-Female", label: "en-ZA-LeahNeural (Female)", gender: "Female", lang: "en-ZA" },
  { value: "en-ZA-LukeNeural-Male", label: "en-ZA-LukeNeural (Male)", gender: "Male", lang: "en-ZA" },
  { value: "es-AR-ElenaNeural-Female", label: "es-AR-ElenaNeural (Female)", gender: "Female", lang: "es-AR" },
  { value: "es-AR-TomasNeural-Male", label: "es-AR-TomasNeural (Male)", gender: "Male", lang: "es-AR" },
  { value: "es-BO-MarceloNeural-Male", label: "es-BO-MarceloNeural (Male)", gender: "Male", lang: "es-BO" },
  { value: "es-BO-SofiaNeural-Female", label: "es-BO-SofiaNeural (Female)", gender: "Female", lang: "es-BO" },
  { value: "es-CL-CatalinaNeural-Female", label: "es-CL-CatalinaNeural (Female)", gender: "Female", lang: "es-CL" },
  { value: "es-CL-LorenzoNeural-Male", label: "es-CL-LorenzoNeural (Male)", gender: "Male", lang: "es-CL" },
  { value: "es-CO-GonzaloNeural-Male", label: "es-CO-GonzaloNeural (Male)", gender: "Male", lang: "es-CO" },
  { value: "es-CO-SalomeNeural-Female", label: "es-CO-SalomeNeural (Female)", gender: "Female", lang: "es-CO" },
  { value: "es-CR-JuanNeural-Male", label: "es-CR-JuanNeural (Male)", gender: "Male", lang: "es-CR" },
  { value: "es-CR-MariaNeural-Female", label: "es-CR-MariaNeural (Female)", gender: "Female", lang: "es-CR" },
  { value: "es-CU-BelkysNeural-Female", label: "es-CU-BelkysNeural (Female)", gender: "Female", lang: "es-CU" },
  { value: "es-CU-ManuelNeural-Male", label: "es-CU-ManuelNeural (Male)", gender: "Male", lang: "es-CU" },
  { value: "es-DO-EmilioNeural-Male", label: "es-DO-EmilioNeural (Male)", gender: "Male", lang: "es-DO" },
  { value: "es-DO-RamonaNeural-Female", label: "es-DO-RamonaNeural (Female)", gender: "Female", lang: "es-DO" },
  { value: "es-EC-AndreaNeural-Female", label: "es-EC-AndreaNeural (Female)", gender: "Female", lang: "es-EC" },
  { value: "es-EC-LuisNeural-Male", label: "es-EC-LuisNeural (Male)", gender: "Male", lang: "es-EC" },
  { value: "es-ES-AlvaroNeural-Male", label: "es-ES-AlvaroNeural (Male)", gender: "Male", lang: "es-ES" },
  { value: "es-ES-ElviraNeural-Female", label: "es-ES-ElviraNeural (Female)", gender: "Female", lang: "es-ES" },
  { value: "es-ES-XimenaNeural-Female", label: "es-ES-XimenaNeural (Female)", gender: "Female", lang: "es-ES" },
  { value: "es-GQ-JavierNeural-Male", label: "es-GQ-JavierNeural (Male)", gender: "Male", lang: "es-GQ" },
  { value: "es-GQ-TeresaNeural-Female", label: "es-GQ-TeresaNeural (Female)", gender: "Female", lang: "es-GQ" },
  { value: "es-GT-AndresNeural-Male", label: "es-GT-AndresNeural (Male)", gender: "Male", lang: "es-GT" },
  { value: "es-GT-MartaNeural-Female", label: "es-GT-MartaNeural (Female)", gender: "Female", lang: "es-GT" },
  { value: "es-HN-CarlosNeural-Male", label: "es-HN-CarlosNeural (Male)", gender: "Male", lang: "es-HN" },
  { value: "es-HN-KarlaNeural-Female", label: "es-HN-KarlaNeural (Female)", gender: "Female", lang: "es-HN" },
  { value: "es-MX-DaliaNeural-Female", label: "es-MX-DaliaNeural (Female)", gender: "Female", lang: "es-MX" },
  { value: "es-MX-JorgeNeural-Male", label: "es-MX-JorgeNeural (Male)", gender: "Male", lang: "es-MX" },
  { value: "es-NI-FedericoNeural-Male", label: "es-NI-FedericoNeural (Male)", gender: "Male", lang: "es-NI" },
  { value: "es-NI-YolandaNeural-Female", label: "es-NI-YolandaNeural (Female)", gender: "Female", lang: "es-NI" },
  { value: "es-PA-MargaritaNeural-Female", label: "es-PA-MargaritaNeural (Female)", gender: "Female", lang: "es-PA" },
  { value: "es-PA-RobertoNeural-Male", label: "es-PA-RobertoNeural (Male)", gender: "Male", lang: "es-PA" },
  { value: "es-PE-AlexNeural-Male", label: "es-PE-AlexNeural (Male)", gender: "Male", lang: "es-PE" },
  { value: "es-PE-CamilaNeural-Female", label: "es-PE-CamilaNeural (Female)", gender: "Female", lang: "es-PE" },
  { value: "es-PR-KarinaNeural-Female", label: "es-PR-KarinaNeural (Female)", gender: "Female", lang: "es-PR" },
  { value: "es-PR-VictorNeural-Male", label: "es-PR-VictorNeural (Male)", gender: "Male", lang: "es-PR" },
  { value: "es-PY-MarioNeural-Male", label: "es-PY-MarioNeural (Male)", gender: "Male", lang: "es-PY" },
  { value: "es-PY-TaniaNeural-Female", label: "es-PY-TaniaNeural (Female)", gender: "Female", lang: "es-PY" },
  { value: "es-SV-LorenaNeural-Female", label: "es-SV-LorenaNeural (Female)", gender: "Female", lang: "es-SV" },
  { value: "es-SV-RodrigoNeural-Male", label: "es-SV-RodrigoNeural (Male)", gender: "Male", lang: "es-SV" },
  { value: "es-US-AlonsoNeural-Male", label: "es-US-AlonsoNeural (Male)", gender: "Male", lang: "es-US" },
  { value: "es-US-PalomaNeural-Female", label: "es-US-PalomaNeural (Female)", gender: "Female", lang: "es-US" },
  { value: "es-UY-MateoNeural-Male", label: "es-UY-MateoNeural (Male)", gender: "Male", lang: "es-UY" },
  { value: "es-UY-ValentinaNeural-Female", label: "es-UY-ValentinaNeural (Female)", gender: "Female", lang: "es-UY" },
  { value: "es-VE-PaolaNeural-Female", label: "es-VE-PaolaNeural (Female)", gender: "Female", lang: "es-VE" },
  { value: "es-VE-SebastianNeural-Male", label: "es-VE-SebastianNeural (Male)", gender: "Male", lang: "es-VE" },
  { value: "et-EE-AnuNeural-Female", label: "et-EE-AnuNeural (Female)", gender: "Female", lang: "et-EE" },
  { value: "et-EE-KertNeural-Male", label: "et-EE-KertNeural (Male)", gender: "Male", lang: "et-EE" },
  { value: "fa-IR-DilaraNeural-Female", label: "fa-IR-DilaraNeural (Female)", gender: "Female", lang: "fa-IR" },
  { value: "fa-IR-FaridNeural-Male", label: "fa-IR-FaridNeural (Male)", gender: "Male", lang: "fa-IR" },
  { value: "fi-FI-HarriNeural-Male", label: "fi-FI-HarriNeural (Male)", gender: "Male", lang: "fi-FI" },
  { value: "fi-FI-NooraNeural-Female", label: "fi-FI-NooraNeural (Female)", gender: "Female", lang: "fi-FI" },
  { value: "fil-PH-AngeloNeural-Male", label: "fil-PH-AngeloNeural (Male)", gender: "Male", lang: "fil-PH" },
  { value: "fil-PH-BlessicaNeural-Female", label: "fil-PH-BlessicaNeural (Female)", gender: "Female", lang: "fil-PH" },
  { value: "fr-BE-CharlineNeural-Female", label: "fr-BE-CharlineNeural (Female)", gender: "Female", lang: "fr-BE" },
  { value: "fr-BE-GerardNeural-Male", label: "fr-BE-GerardNeural (Male)", gender: "Male", lang: "fr-BE" },
  { value: "fr-CA-AntoineNeural-Male", label: "fr-CA-AntoineNeural (Male)", gender: "Male", lang: "fr-CA" },
  { value: "fr-CA-JeanNeural-Male", label: "fr-CA-JeanNeural (Male)", gender: "Male", lang: "fr-CA" },
  { value: "fr-CA-SylvieNeural-Female", label: "fr-CA-SylvieNeural (Female)", gender: "Female", lang: "fr-CA" },
  { value: "fr-CA-ThierryNeural-Male", label: "fr-CA-ThierryNeural (Male)", gender: "Male", lang: "fr-CA" },
  { value: "fr-CH-ArianeNeural-Female", label: "fr-CH-ArianeNeural (Female)", gender: "Female", lang: "fr-CH" },
  { value: "fr-CH-FabriceNeural-Male", label: "fr-CH-FabriceNeural (Male)", gender: "Male", lang: "fr-CH" },
  { value: "fr-FR-DeniseNeural-Female", label: "fr-FR-DeniseNeural (Female)", gender: "Female", lang: "fr-FR" },
  { value: "fr-FR-EloiseNeural-Female", label: "fr-FR-EloiseNeural (Female)", gender: "Female", lang: "fr-FR" },
  { value: "fr-FR-HenriNeural-Male", label: "fr-FR-HenriNeural (Male)", gender: "Male", lang: "fr-FR" },
  { value: "fr-FR-RemyMultilingualNeural-Male", label: "fr-FR-RemyMultilingualNeural (Male)", gender: "Male", lang: "fr-FR" },
  { value: "fr-FR-VivienneMultilingualNeural-Female", label: "fr-FR-VivienneMultilingualNeural (Female)", gender: "Female", lang: "fr-FR" },
  { value: "ga-IE-ColmNeural-Male", label: "ga-IE-ColmNeural (Male)", gender: "Male", lang: "ga-IE" },
  { value: "ga-IE-OrlaNeural-Female", label: "ga-IE-OrlaNeural (Female)", gender: "Female", lang: "ga-IE" },
  { value: "gl-ES-RoiNeural-Male", label: "gl-ES-RoiNeural (Male)", gender: "Male", lang: "gl-ES" },
  { value: "gl-ES-SabelaNeural-Female", label: "gl-ES-SabelaNeural (Female)", gender: "Female", lang: "gl-ES" },
  { value: "gu-IN-DhwaniNeural-Female", label: "gu-IN-DhwaniNeural (Female)", gender: "Female", lang: "gu-IN" },
  { value: "gu-IN-NiranjanNeural-Male", label: "gu-IN-NiranjanNeural (Male)", gender: "Male", lang: "gu-IN" },
  { value: "he-IL-AvriNeural-Male", label: "he-IL-AvriNeural (Male)", gender: "Male", lang: "he-IL" },
  { value: "he-IL-HilaNeural-Female", label: "he-IL-HilaNeural (Female)", gender: "Female", lang: "he-IL" },
  { value: "hi-IN-MadhurNeural-Male", label: "hi-IN-MadhurNeural (Male)", gender: "Male", lang: "hi-IN" },
  { value: "hi-IN-SwaraNeural-Female", label: "hi-IN-SwaraNeural (Female)", gender: "Female", lang: "hi-IN" },
  { value: "hr-HR-GabrijelaNeural-Female", label: "hr-HR-GabrijelaNeural (Female)", gender: "Female", lang: "hr-HR" },
  { value: "hr-HR-SreckoNeural-Male", label: "hr-HR-SreckoNeural (Male)", gender: "Male", lang: "hr-HR" },
  { value: "hu-HU-NoemiNeural-Female", label: "hu-HU-NoemiNeural (Female)", gender: "Female", lang: "hu-HU" },
  { value: "hu-HU-TamasNeural-Male", label: "hu-HU-TamasNeural (Male)", gender: "Male", lang: "hu-HU" },
  { value: "id-ID-ArdiNeural-Male", label: "id-ID-ArdiNeural (Male)", gender: "Male", lang: "id-ID" },
  { value: "id-ID-GadisNeural-Female", label: "id-ID-GadisNeural (Female)", gender: "Female", lang: "id-ID" },
  { value: "is-IS-GudrunNeural-Female", label: "is-IS-GudrunNeural (Female)", gender: "Female", lang: "is-IS" },
  { value: "is-IS-GunnarNeural-Male", label: "is-IS-GunnarNeural (Male)", gender: "Male", lang: "is-IS" },
  { value: "it-IT-DiegoNeural-Male", label: "it-IT-DiegoNeural (Male)", gender: "Male", lang: "it-IT" },
  { value: "it-IT-ElsaNeural-Female", label: "it-IT-ElsaNeural (Female)", gender: "Female", lang: "it-IT" },
  { value: "it-IT-GiuseppeMultilingualNeural-Male", label: "it-IT-GiuseppeMultilingualNeural (Male)", gender: "Male", lang: "it-IT" },
  { value: "it-IT-IsabellaNeural-Female", label: "it-IT-IsabellaNeural (Female)", gender: "Female", lang: "it-IT" },
  { value: "iu-Cans-CA-SiqiniqNeural-Female", label: "iu-Cans-CA-SiqiniqNeural (Female)", gender: "Female", lang: "iu-Cans" },
  { value: "iu-Cans-CA-TaqqiqNeural-Male", label: "iu-Cans-CA-TaqqiqNeural (Male)", gender: "Male", lang: "iu-Cans" },
  { value: "iu-Latn-CA-SiqiniqNeural-Female", label: "iu-Latn-CA-SiqiniqNeural (Female)", gender: "Female", lang: "iu-Latn" },
  { value: "iu-Latn-CA-TaqqiqNeural-Male", label: "iu-Latn-CA-TaqqiqNeural (Male)", gender: "Male", lang: "iu-Latn" },
  { value: "ja-JP-KeitaNeural-Male", label: "ja-JP-KeitaNeural (Male)", gender: "Male", lang: "ja-JP" },
  { value: "ja-JP-NanamiNeural-Female", label: "ja-JP-NanamiNeural (Female)", gender: "Female", lang: "ja-JP" },
  { value: "jv-ID-DimasNeural-Male", label: "jv-ID-DimasNeural (Male)", gender: "Male", lang: "jv-ID" },
  { value: "jv-ID-SitiNeural-Female", label: "jv-ID-SitiNeural (Female)", gender: "Female", lang: "jv-ID" },
  { value: "ka-GE-EkaNeural-Female", label: "ka-GE-EkaNeural (Female)", gender: "Female", lang: "ka-GE" },
  { value: "ka-GE-GiorgiNeural-Male", label: "ka-GE-GiorgiNeural (Male)", gender: "Male", lang: "ka-GE" },
  { value: "kk-KZ-AigulNeural-Female", label: "kk-KZ-AigulNeural (Female)", gender: "Female", lang: "kk-KZ" },
  { value: "kk-KZ-DauletNeural-Male", label: "kk-KZ-DauletNeural (Male)", gender: "Male", lang: "kk-KZ" },
  { value: "km-KH-PisethNeural-Male", label: "km-KH-PisethNeural (Male)", gender: "Male", lang: "km-KH" },
  { value: "km-KH-SreymomNeural-Female", label: "km-KH-SreymomNeural (Female)", gender: "Female", lang: "km-KH" },
  { value: "kn-IN-GaganNeural-Male", label: "kn-IN-GaganNeural (Male)", gender: "Male", lang: "kn-IN" },
  { value: "kn-IN-SapnaNeural-Female", label: "kn-IN-SapnaNeural (Female)", gender: "Female", lang: "kn-IN" },
  { value: "ko-KR-HyunsuMultilingualNeural-Male", label: "ko-KR-HyunsuMultilingualNeural (Male)", gender: "Male", lang: "ko-KR" },
  { value: "ko-KR-InJoonNeural-Male", label: "ko-KR-InJoonNeural (Male)", gender: "Male", lang: "ko-KR" },
  { value: "ko-KR-SunHiNeural-Female", label: "ko-KR-SunHiNeural (Female)", gender: "Female", lang: "ko-KR" },
  { value: "lo-LA-ChanthavongNeural-Male", label: "lo-LA-ChanthavongNeural (Male)", gender: "Male", lang: "lo-LA" },
  { value: "lo-LA-KeomanyNeural-Female", label: "lo-LA-KeomanyNeural (Female)", gender: "Female", lang: "lo-LA" },
  { value: "lt-LT-LeonasNeural-Male", label: "lt-LT-LeonasNeural (Male)", gender: "Male", lang: "lt-LT" },
  { value: "lt-LT-OnaNeural-Female", label: "lt-LT-OnaNeural (Female)", gender: "Female", lang: "lt-LT" },
  { value: "lv-LV-EveritaNeural-Female", label: "lv-LV-EveritaNeural (Female)", gender: "Female", lang: "lv-LV" },
  { value: "lv-LV-NilsNeural-Male", label: "lv-LV-NilsNeural (Male)", gender: "Male", lang: "lv-LV" },
  { value: "mk-MK-AleksandarNeural-Male", label: "mk-MK-AleksandarNeural (Male)", gender: "Male", lang: "mk-MK" },
  { value: "mk-MK-MarijaNeural-Female", label: "mk-MK-MarijaNeural (Female)", gender: "Female", lang: "mk-MK" },
  { value: "ml-IN-MidhunNeural-Male", label: "ml-IN-MidhunNeural (Male)", gender: "Male", lang: "ml-IN" },
  { value: "ml-IN-SobhanaNeural-Female", label: "ml-IN-SobhanaNeural (Female)", gender: "Female", lang: "ml-IN" },
  { value: "mn-MN-BataaNeural-Male", label: "mn-MN-BataaNeural (Male)", gender: "Male", lang: "mn-MN" },
  { value: "mn-MN-YesuiNeural-Female", label: "mn-MN-YesuiNeural (Female)", gender: "Female", lang: "mn-MN" },
  { value: "mr-IN-AarohiNeural-Female", label: "mr-IN-AarohiNeural (Female)", gender: "Female", lang: "mr-IN" },
  { value: "mr-IN-ManoharNeural-Male", label: "mr-IN-ManoharNeural (Male)", gender: "Male", lang: "mr-IN" },
  { value: "ms-MY-OsmanNeural-Male", label: "ms-MY-OsmanNeural (Male)", gender: "Male", lang: "ms-MY" },
  { value: "ms-MY-YasminNeural-Female", label: "ms-MY-YasminNeural (Female)", gender: "Female", lang: "ms-MY" },
  { value: "mt-MT-GraceNeural-Female", label: "mt-MT-GraceNeural (Female)", gender: "Female", lang: "mt-MT" },
  { value: "mt-MT-JosephNeural-Male", label: "mt-MT-JosephNeural (Male)", gender: "Male", lang: "mt-MT" },
  { value: "my-MM-NilarNeural-Female", label: "my-MM-NilarNeural (Female)", gender: "Female", lang: "my-MM" },
  { value: "my-MM-ThihaNeural-Male", label: "my-MM-ThihaNeural (Male)", gender: "Male", lang: "my-MM" },
  { value: "nb-NO-FinnNeural-Male", label: "nb-NO-FinnNeural (Male)", gender: "Male", lang: "nb-NO" },
  { value: "nb-NO-PernilleNeural-Female", label: "nb-NO-PernilleNeural (Female)", gender: "Female", lang: "nb-NO" },
  { value: "ne-NP-HemkalaNeural-Female", label: "ne-NP-HemkalaNeural (Female)", gender: "Female", lang: "ne-NP" },
  { value: "ne-NP-SagarNeural-Male", label: "ne-NP-SagarNeural (Male)", gender: "Male", lang: "ne-NP" },
  { value: "nl-BE-ArnaudNeural-Male", label: "nl-BE-ArnaudNeural (Male)", gender: "Male", lang: "nl-BE" },
  { value: "nl-BE-DenaNeural-Female", label: "nl-BE-DenaNeural (Female)", gender: "Female", lang: "nl-BE" },
  { value: "nl-NL-ColetteNeural-Female", label: "nl-NL-ColetteNeural (Female)", gender: "Female", lang: "nl-NL" },
  { value: "nl-NL-FennaNeural-Female", label: "nl-NL-FennaNeural (Female)", gender: "Female", lang: "nl-NL" },
  { value: "nl-NL-MaartenNeural-Male", label: "nl-NL-MaartenNeural (Male)", gender: "Male", lang: "nl-NL" },
  { value: "pl-PL-MarekNeural-Male", label: "pl-PL-MarekNeural (Male)", gender: "Male", lang: "pl-PL" },
  { value: "pl-PL-ZofiaNeural-Female", label: "pl-PL-ZofiaNeural (Female)", gender: "Female", lang: "pl-PL" },
  { value: "ps-AF-GulNawazNeural-Male", label: "ps-AF-GulNawazNeural (Male)", gender: "Male", lang: "ps-AF" },
  { value: "ps-AF-LatifaNeural-Female", label: "ps-AF-LatifaNeural (Female)", gender: "Female", lang: "ps-AF" },
  { value: "pt-BR-AntonioNeural-Male", label: "pt-BR-AntonioNeural (Male)", gender: "Male", lang: "pt-BR" },
  { value: "pt-BR-FranciscaNeural-Female", label: "pt-BR-FranciscaNeural (Female)", gender: "Female", lang: "pt-BR" },
  { value: "pt-BR-ThalitaMultilingualNeural-Female", label: "pt-BR-ThalitaMultilingualNeural (Female)", gender: "Female", lang: "pt-BR" },
  { value: "pt-PT-DuarteNeural-Male", label: "pt-PT-DuarteNeural (Male)", gender: "Male", lang: "pt-PT" },
  { value: "pt-PT-RaquelNeural-Female", label: "pt-PT-RaquelNeural (Female)", gender: "Female", lang: "pt-PT" },
  { value: "ro-RO-AlinaNeural-Female", label: "ro-RO-AlinaNeural (Female)", gender: "Female", lang: "ro-RO" },
  { value: "ro-RO-EmilNeural-Male", label: "ro-RO-EmilNeural (Male)", gender: "Male", lang: "ro-RO" },
  { value: "ru-RU-DmitryNeural-Male", label: "ru-RU-DmitryNeural (Male)", gender: "Male", lang: "ru-RU" },
  { value: "ru-RU-SvetlanaNeural-Female", label: "ru-RU-SvetlanaNeural (Female)", gender: "Female", lang: "ru-RU" },
  { value: "si-LK-SameeraNeural-Male", label: "si-LK-SameeraNeural (Male)", gender: "Male", lang: "si-LK" },
  { value: "si-LK-ThiliniNeural-Female", label: "si-LK-ThiliniNeural (Female)", gender: "Female", lang: "si-LK" },
  { value: "sk-SK-LukasNeural-Male", label: "sk-SK-LukasNeural (Male)", gender: "Male", lang: "sk-SK" },
  { value: "sk-SK-ViktoriaNeural-Female", label: "sk-SK-ViktoriaNeural (Female)", gender: "Female", lang: "sk-SK" },
  { value: "sl-SI-PetraNeural-Female", label: "sl-SI-PetraNeural (Female)", gender: "Female", lang: "sl-SI" },
  { value: "sl-SI-RokNeural-Male", label: "sl-SI-RokNeural (Male)", gender: "Male", lang: "sl-SI" },
  { value: "so-SO-MuuseNeural-Male", label: "so-SO-MuuseNeural (Male)", gender: "Male", lang: "so-SO" },
  { value: "so-SO-UbaxNeural-Female", label: "so-SO-UbaxNeural (Female)", gender: "Female", lang: "so-SO" },
  { value: "sq-AL-AnilaNeural-Female", label: "sq-AL-AnilaNeural (Female)", gender: "Female", lang: "sq-AL" },
  { value: "sq-AL-IlirNeural-Male", label: "sq-AL-IlirNeural (Male)", gender: "Male", lang: "sq-AL" },
  { value: "sr-RS-NicholasNeural-Male", label: "sr-RS-NicholasNeural (Male)", gender: "Male", lang: "sr-RS" },
  { value: "sr-RS-SophieNeural-Female", label: "sr-RS-SophieNeural (Female)", gender: "Female", lang: "sr-RS" },
  { value: "su-ID-JajangNeural-Male", label: "su-ID-JajangNeural (Male)", gender: "Male", lang: "su-ID" },
  { value: "su-ID-TutiNeural-Female", label: "su-ID-TutiNeural (Female)", gender: "Female", lang: "su-ID" },
  { value: "sv-SE-MattiasNeural-Male", label: "sv-SE-MattiasNeural (Male)", gender: "Male", lang: "sv-SE" },
  { value: "sv-SE-SofieNeural-Female", label: "sv-SE-SofieNeural (Female)", gender: "Female", lang: "sv-SE" },
  { value: "sw-KE-RafikiNeural-Male", label: "sw-KE-RafikiNeural (Male)", gender: "Male", lang: "sw-KE" },
  { value: "sw-KE-ZuriNeural-Female", label: "sw-KE-ZuriNeural (Female)", gender: "Female", lang: "sw-KE" },
  { value: "sw-TZ-DaudiNeural-Male", label: "sw-TZ-DaudiNeural (Male)", gender: "Male", lang: "sw-TZ" },
  { value: "sw-TZ-RehemaNeural-Female", label: "sw-TZ-RehemaNeural (Female)", gender: "Female", lang: "sw-TZ" },
  { value: "ta-IN-PallaviNeural-Female", label: "ta-IN-PallaviNeural (Female)", gender: "Female", lang: "ta-IN" },
  { value: "ta-IN-ValluvarNeural-Male", label: "ta-IN-ValluvarNeural (Male)", gender: "Male", lang: "ta-IN" },
  { value: "ta-LK-KumarNeural-Male", label: "ta-LK-KumarNeural (Male)", gender: "Male", lang: "ta-LK" },
  { value: "ta-LK-SaranyaNeural-Female", label: "ta-LK-SaranyaNeural (Female)", gender: "Female", lang: "ta-LK" },
  { value: "ta-MY-KaniNeural-Female", label: "ta-MY-KaniNeural (Female)", gender: "Female", lang: "ta-MY" },
  { value: "ta-MY-SuryaNeural-Male", label: "ta-MY-SuryaNeural (Male)", gender: "Male", lang: "ta-MY" },
  { value: "ta-SG-AnbuNeural-Male", label: "ta-SG-AnbuNeural (Male)", gender: "Male", lang: "ta-SG" },
  { value: "ta-SG-VenbaNeural-Female", label: "ta-SG-VenbaNeural (Female)", gender: "Female", lang: "ta-SG" },
  { value: "te-IN-MohanNeural-Male", label: "te-IN-MohanNeural (Male)", gender: "Male", lang: "te-IN" },
  { value: "te-IN-ShrutiNeural-Female", label: "te-IN-ShrutiNeural (Female)", gender: "Female", lang: "te-IN" },
  { value: "th-TH-NiwatNeural-Male", label: "th-TH-NiwatNeural (Male)", gender: "Male", lang: "th-TH" },
  { value: "th-TH-PremwadeeNeural-Female", label: "th-TH-PremwadeeNeural (Female)", gender: "Female", lang: "th-TH" },
  { value: "tr-TR-AhmetNeural-Male", label: "tr-TR-AhmetNeural (Male)", gender: "Male", lang: "tr-TR" },
  { value: "tr-TR-EmelNeural-Female", label: "tr-TR-EmelNeural (Female)", gender: "Female", lang: "tr-TR" },
  { value: "uk-UA-OstapNeural-Male", label: "uk-UA-OstapNeural (Male)", gender: "Male", lang: "uk-UA" },
  { value: "uk-UA-PolinaNeural-Female", label: "uk-UA-PolinaNeural (Female)", gender: "Female", lang: "uk-UA" },
  { value: "ur-IN-GulNeural-Female", label: "ur-IN-GulNeural (Female)", gender: "Female", lang: "ur-IN" },
  { value: "ur-IN-SalmanNeural-Male", label: "ur-IN-SalmanNeural (Male)", gender: "Male", lang: "ur-IN" },
  { value: "ur-PK-AsadNeural-Male", label: "ur-PK-AsadNeural (Male)", gender: "Male", lang: "ur-PK" },
  { value: "ur-PK-UzmaNeural-Female", label: "ur-PK-UzmaNeural (Female)", gender: "Female", lang: "ur-PK" },
  { value: "uz-UZ-MadinaNeural-Female", label: "uz-UZ-MadinaNeural (Female)", gender: "Female", lang: "uz-UZ" },
  { value: "uz-UZ-SardorNeural-Male", label: "uz-UZ-SardorNeural (Male)", gender: "Male", lang: "uz-UZ" },
  { value: "vi-VN-HoaiMyNeural-Female", label: "vi-VN-HoaiMyNeural (Female)", gender: "Female", lang: "vi-VN" },
  { value: "vi-VN-NamMinhNeural-Male", label: "vi-VN-NamMinhNeural (Male)", gender: "Male", lang: "vi-VN" },
  { value: "zh-CN-XiaoxiaoNeural-Female", label: "zh-CN-XiaoxiaoNeural (Female)", gender: "Female", lang: "zh-CN" },
  { value: "zh-CN-XiaoyiNeural-Female", label: "zh-CN-XiaoyiNeural (Female)", gender: "Female", lang: "zh-CN" },
  { value: "zh-CN-YunjianNeural-Male", label: "zh-CN-YunjianNeural (Male)", gender: "Male", lang: "zh-CN" },
  { value: "zh-CN-YunxiNeural-Male", label: "zh-CN-YunxiNeural (Male)", gender: "Male", lang: "zh-CN" },
  { value: "zh-CN-YunxiaNeural-Male", label: "zh-CN-YunxiaNeural (Male)", gender: "Male", lang: "zh-CN" },
  { value: "zh-CN-YunyangNeural-Male", label: "zh-CN-YunyangNeural (Male)", gender: "Male", lang: "zh-CN" },
  { value: "zh-CN-liaoning-XiaobeiNeural-Female", label: "zh-CN-liaoning-XiaobeiNeural (Female)", gender: "Female", lang: "zh-CN" },
  { value: "zh-CN-shaanxi-XiaoniNeural-Female", label: "zh-CN-shaanxi-XiaoniNeural (Female)", gender: "Female", lang: "zh-CN" },
  { value: "zh-HK-HiuGaaiNeural-Female", label: "zh-HK-HiuGaaiNeural (Female)", gender: "Female", lang: "zh-HK" },
  { value: "zh-HK-HiuMaanNeural-Female", label: "zh-HK-HiuMaanNeural (Female)", gender: "Female", lang: "zh-HK" },
  { value: "zh-HK-WanLungNeural-Male", label: "zh-HK-WanLungNeural (Male)", gender: "Male", lang: "zh-HK" },
  { value: "zh-TW-HsiaoChenNeural-Female", label: "zh-TW-HsiaoChenNeural (Female)", gender: "Female", lang: "zh-TW" },
  { value: "zh-TW-HsiaoYuNeural-Female", label: "zh-TW-HsiaoYuNeural (Female)", gender: "Female", lang: "zh-TW" },
  { value: "zh-TW-YunJheNeural-Male", label: "zh-TW-YunJheNeural (Male)", gender: "Male", lang: "zh-TW" },
  { value: "zu-ZA-ThandoNeural-Female", label: "zu-ZA-ThandoNeural (Female)", gender: "Female", lang: "zu-ZA" },
  { value: "zu-ZA-ThembaNeural-Male", label: "zu-ZA-ThembaNeural (Male)", gender: "Male", lang: "zu-ZA" },
  { value: "en-US-AvaMultilingualNeural-V2-Female", label: "en-US-AvaMultilingualNeural-V2 (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-AndrewMultilingualNeural-V2-Male", label: "en-US-AndrewMultilingualNeural-V2 (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-EmmaMultilingualNeural-V2-Female", label: "en-US-EmmaMultilingualNeural-V2 (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-BrianMultilingualNeural-V2-Male", label: "en-US-BrianMultilingualNeural-V2 (Male)", gender: "Male", lang: "en-US" },
  { value: "de-DE-FlorianMultilingualNeural-V2-Male", label: "de-DE-FlorianMultilingualNeural-V2 (Male)", gender: "Male", lang: "de-DE" },
  { value: "de-DE-SeraphinaMultilingualNeural-V2-Female", label: "de-DE-SeraphinaMultilingualNeural-V2 (Female)", gender: "Female", lang: "de-DE" },
  { value: "fr-FR-RemyMultilingualNeural-V2-Male", label: "fr-FR-RemyMultilingualNeural-V2 (Male)", gender: "Male", lang: "fr-FR" },
  { value: "fr-FR-VivienneMultilingualNeural-V2-Female", label: "fr-FR-VivienneMultilingualNeural-V2 (Female)", gender: "Female", lang: "fr-FR" },
  { value: "zh-CN-XiaoxiaoMultilingualNeural-V2-Female", label: "zh-CN-XiaoxiaoMultilingualNeural-V2 (Female)", gender: "Female", lang: "zh-CN" }
];

// Azure V2 multilingual voices
export const AZURE_V2_VOICES: Voice[] = [
  { value: "zh-CN-XiaoxiaoMultilingualNeural-V2-Female", label: "XiaoxiaoMultilingual V2 (Female)", gender: "Female", lang: "zh-CN" },
  { value: "zh-CN-YunxiMultilingualNeural-V2-Male", label: "YunxiMultilingual V2 (Male)", gender: "Male", lang: "zh-CN" },
  { value: "en-US-AvaMultilingualNeural-V2-Female", label: "AvaMultilingual V2 (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-AndrewMultilingualNeural-V2-Male", label: "AndrewMultilingual V2 (Male)", gender: "Male", lang: "en-US" },
  { value: "en-US-EmmaMultilingualNeural-V2-Female", label: "EmmaMultilingual V2 (Female)", gender: "Female", lang: "en-US" },
  { value: "en-US-BrianMultilingualNeural-V2-Male", label: "BrianMultilingual V2 (Male)", gender: "Male", lang: "en-US" },
  { value: "fr-FR-RemyMultilingualNeural-V2-Male", label: "RemyMultilingual V2 (Male)", gender: "Male", lang: "fr-FR" },
  { value: "de-DE-SeraphinaMultilingualNeural-V2-Female", label: "SeraphinaMultilingual V2 (Female)", gender: "Female", lang: "de-DE" },
  { value: "ja-JP-MasaruMultilingualNeural-V2-Male", label: "MasaruMultilingual V2 (Male)", gender: "Male", lang: "ja-JP" },
];

export const SILICONFLOW_VOICES: Voice[] = [
  { value: "siliconflow:FunAudioLLM/CosyVoice2-0.5B:alex-Male", label: "Alex (Male)", gender: "Male", lang: "zh-CN" },
  { value: "siliconflow:FunAudioLLM/CosyVoice2-0.5B:anna-Female", label: "Anna (Female)", gender: "Female", lang: "zh-CN" },
  { value: "siliconflow:FunAudioLLM/CosyVoice2-0.5B:bella-Female", label: "Bella (Female)", gender: "Female", lang: "zh-CN" },
  { value: "siliconflow:FunAudioLLM/CosyVoice2-0.5B:benjamin-Male", label: "Benjamin (Male)", gender: "Male", lang: "zh-CN" },
  { value: "siliconflow:FunAudioLLM/CosyVoice2-0.5B:charles-Male", label: "Charles (Male)", gender: "Male", lang: "zh-CN" },
  { value: "siliconflow:FunAudioLLM/CosyVoice2-0.5B:claire-Female", label: "Claire (Female)", gender: "Female", lang: "zh-CN" },
  { value: "siliconflow:FunAudioLLM/CosyVoice2-0.5B:david-Male", label: "David (Male)", gender: "Male", lang: "zh-CN" },
  { value: "siliconflow:FunAudioLLM/CosyVoice2-0.5B:diana-Female", label: "Diana (Female)", gender: "Female", lang: "zh-CN" },
];

export const GEMINI_VOICES: Voice[] = [
  { value: "gemini:Zephyr-Female", label: "Zephyr (Female)", gender: "Female", lang: "en-US" },
  { value: "gemini:Puck-Male", label: "Puck (Male)", gender: "Male", lang: "en-US" },
  { value: "gemini:Charon-Male", label: "Charon (Male)", gender: "Male", lang: "en-US" },
  { value: "gemini:Kore-Female", label: "Kore (Female)", gender: "Female", lang: "en-US" },
  { value: "gemini:Fenrir-Male", label: "Fenrir (Male)", gender: "Male", lang: "en-US" },
  { value: "gemini:Aoede-Female", label: "Aoede (Female)", gender: "Female", lang: "en-US" },
  { value: "gemini:Thalia-Female", label: "Thalia (Female)", gender: "Female", lang: "en-US" },
  { value: "gemini:Sage-Male", label: "Sage (Male)", gender: "Male", lang: "en-US" },
  { value: "gemini:Echo-Female", label: "Echo (Female)", gender: "Female", lang: "en-US" },
  { value: "gemini:Harmony-Female", label: "Harmony (Female)", gender: "Female", lang: "en-US" },
  { value: "gemini:Lux-Female", label: "Lux (Female)", gender: "Female", lang: "en-US" },
  { value: "gemini:Nova-Female", label: "Nova (Female)", gender: "Female", lang: "en-US" },
  { value: "gemini:Vale-Male", label: "Vale (Male)", gender: "Male", lang: "en-US" },
  { value: "gemini:Orion-Male", label: "Orion (Male)", gender: "Male", lang: "en-US" },
  { value: "gemini:Atlas-Male", label: "Atlas (Male)", gender: "Male", lang: "en-US" },
];

export const MIMO_VOICES: Voice[] = [
  { value: "mimo:mimo_default-Female", label: "Default (Female)", gender: "Female", lang: "zh-CN" },
  { value: "mimo:冰糖-Female", label: "冰糖 (Female)", gender: "Female", lang: "zh-CN" },
  { value: "mimo:茉莉-Female", label: "茉莉 (Female)", gender: "Female", lang: "zh-CN" },
  { value: "mimo:苏打-Male", label: "苏打 (Male)", gender: "Male", lang: "zh-CN" },
  { value: "mimo:白桦-Male", label: "白桦 (Male)", gender: "Male", lang: "zh-CN" },
  { value: "mimo:Mia-Female", label: "Mia (Female)", gender: "Female", lang: "zh-CN" },
  { value: "mimo:Chloe-Female", label: "Chloe (Female)", gender: "Female", lang: "zh-CN" },
  { value: "mimo:Milo-Male", label: "Milo (Male)", gender: "Male", lang: "zh-CN" },
  { value: "mimo:Dean-Male", label: "Dean (Male)", gender: "Male", lang: "zh-CN" },
];

export function getVoicesForServer(server: TtsServer): Voice[] {
  switch (server) {
    case "azure-tts-v1": return AZURE_VOICES;
    case "azure-tts-v2": return AZURE_V2_VOICES;
    case "siliconflow": return SILICONFLOW_VOICES;
    case "gemini": return GEMINI_VOICES;
    case "mimo": return MIMO_VOICES;
    default: return [];
  }
}

export function getUniqueLanguages(voices: Voice[]): string[] {
  return Array.from(new Set(voices.map((v) => v.lang))).sort();
}
